import java.util.HashMap;
import java.util.Map;

/*
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:
 */



class usinghashmap {
	
	
	public static void main(String[] args) {
	char ch=	findTheDifference("ganesh","ganezsh");
		System.out.println(ch);
	}
	
	
    public static char findTheDifference(String s, String t) {
    	
    	
         s=s.concat(t);
         char [] arr=s.toCharArray();
         	Map <Character,Integer>maps=new HashMap<>();
         	
         	for(int i=0;i<arr.length;i++)
         	{
         		if(maps.containsKey(s.charAt(i)))
         		{
         			maps.put(s.charAt(i), maps.get(s.charAt(i))+1);
         		}
         		else
         		{
         			maps.put(s.charAt(i), 1);
         		}
         	}
         	
         	for(int i=0;i<arr.length;i++)
         	{
         		if(maps.get(s.charAt(i))==1 || maps.get(s.charAt(i))==3)
         		{
         			return arr[i];
         		}
         	}
         
         
    	
    
		return 0;
        
    }
}