import java.util.HashMap;
import java.util.Map;

/*
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:
 */



class usingarray {
	
	
	public static void main(String[] args) {
	char ch=	findTheDifference("ganesh","gnesh");
		System.out.println(ch);
	}
	
	
    public static char findTheDifference(String s, String t) {
    	
    	
    	int [] fre=new int[26];
         s=s.concat(t);
         char [] arr=s.toCharArray();
         	
         	
         	for(char c:arr)
         	{
         		fre[c-'a']++;
         	}
         	
         	for(int i=0;i<arr.length;i++)
         	{
         		if(fre[arr[i]-'a']==1)
         		{
         			return arr[i];
         		}
         	}
         	
         	
    	
    	
		return 0;
        
    }
}